<?php namespace ProcessWire;

use CstkItemQuery, CstkItem;

use Propel\Runtime\ActiveQuery\Criteria;

class FilterItemsCstk extends WireData implements Module {
	/**
	 * Returns Query
	 * @return CstkItemQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = CstkItemQuery::create();
	}

	/**
	 * Filter Query by CSTK cell values
	 * @param  string $custID   Customer ID
	 * @param  string $shiptoID Customer Shipto ID
	 * @param  string $cell     Cell
	 * @return void
	 */
	public function cstkcell($custID, $shiptoID = '', $cell) {
		$this->query->filterByCustid($custID);
		$this->query->filterByShiptoid($shiptoID);
		$this->query->filterByCell($cell);
	}

	/**
	 * Searches the CstkItem Table to find vendors that match the query provided
	 * @param  string $q Search Query
	 * @return void
	 */
	public function search($q) {
		$columns = array(
			CstkItem::get_aliasproperty('itemid'),
			CstkItem::get_aliasproperty('custitemid'),
		);
		$this->query->search_filter($columns, strtoupper($q));
	}

	/**
	 * Adds the Sort By to the query
	 * @param  Page   $page
	 * @return void
	 */
	public function sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;

			$tablecolumn = CstkItem::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Filter CSTK Items Module',
			'version' => 101,
			'summary' => 'Handles CSTK Items Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
