<?php namespace ProcessWire;

use VmiOrderQuery, VmiOrder;

use Propel\Runtime\ActiveQuery\Criteria;

class FilterItemsVmiOrdered extends WireData implements Module {
	/**
	 * Returns Query
	 * @return VmiOrderQuery
	 */
	public function get_query() {
		return $this->query;
	}

	/**
	 * Initializes Query
	 * @param  User   $user User to Check if they are a Sales Person
	 * @return void
	 */
	public function init_query(User $user) {
		$this->query = VmiOrderQuery::create();
	}

	/**
	 * Filter Query by CSTK cell values
	 * @param  string $custID   Customer ID
	 * @param  string $shiptoID Customer Shipto ID
	 * @param  string $cell     Cell
	 * @return void
	 */
	public function cstkcell($custID, $shiptoID = '', $cell) {
		$this->query->filterByCustid($custID);
		$this->query->filterByShiptoid($shiptoID);
		$this->query->filterByCell($cell);
	}

	/**
	 * Searches the VmiOrder Table to find vendors that match the query provided
	 * @param  string $q Search Query
	 * @return void
	 */
	public function search($q) {
		$columns = array(
			VmiOrder::get_aliasproperty('custid'),
			VmiOrder::get_aliasproperty('shiptoid'),
			VmiOrder::get_aliasproperty('cell'),
			VmiOrder::get_aliasproperty('itemid'),
			VmiOrder::get_aliasproperty('custitemid'),
		);
		$this->query->search_filter($columns, strtoupper($q));
	}

	/**
	 * Adds the Sort By to the query
	 * @param  Page   $page
	 * @return void
	 */
	public function sortby(Page $page) {
		if ($page->has_orderby()) {
			$orderbycolumn = $page->orderby_column;
			$sort = $page->orderby_sort;

			$tablecolumn = VmiOrder::get_aliasproperty($orderbycolumn);
			$this->query->sortBy($tablecolumn, $sort);
		}
	}

/* =============================================================
	ProcessWire Module Functions
============================================================= */
	public static function getModuleInfo() {
		return array(
			'title' => 'Dpluso Filter VMI Items Ordered',
			'version' => 101,
			'summary' => 'Handles VMI Items Ordered Filtering',
			'singular' => true,
			'autoload' => true,
		);
	}
}
